### ISSUE TITLE
Correcting errors in papers

### ISSUE THREAD

**Issue by jr011** [sherdencooper/GPTFuzz#1]
The paper says introduce five specialized mutation operators, but only four were introduced: Crossover, Expand, Shorten, Rephrase. The Generate was left behind.

**Comment by sherdencooper** [comment]
Thanks for notifying us! We noticed the error, as well as other typos in the paper. We will update the arxiv paper before this weekend. Thanks again for your careful reading! If you have any issue about the paper or the code, plz let us know!

**Comment by TedLau** [comment]
Looking forward to updates on your paper even though it's not very important~

**Comment by sherdencooper** [comment]
@TedLau Thanks for your patience! We are adding more ablation studies and need more time to revise the paper. After that, we will also adjust our code to make it more module-customizable. Thanks for your understanding and interest in our project!

**Comment by TedLau** [comment]
Thanks, looking forward to your good news~
