### ISSUE TITLE
Mismatch in formula between paper and code

### ISSUE THREAD

**Issue by romanlutz** [sherdencooper/GPTFuzz#31]
The paper shows the following formulas with the term `+ 1`

![image](https://github.com/sherdencooper/GPTFuzz/assets/10245648/8825aacb-bc62-415b-b388-bd47ac36f177)

whereas in the code we always seem to do `+ 0.01`

here https://github.com/sherdencooper/GPTFuzz/blob/745d5fcd9363850ddb3e83f0fd3247ff9e76eae4/gptfuzzer/fuzzer/selection.py#L103
and here
https://github.com/sherdencooper/GPTFuzz/blob/745d5fcd9363850ddb3e83f0fd3247ff9e76eae4/gptfuzzer/fuzzer/selection.py#L115

Am I missing something or is there a particular reason for this difference?

CC @gseetha04 who discovered this.

**Comment by sherdencooper** [comment]
Hi, thanks for your careful reading. The +1/+0.01 is used to prevent the denominator from becoming zero, so they should have similar effects. The reason why I am giving +0.01 is that I thought a smaller denominator would encourage the seed selection algorithm to prioritize those newly found seeds (which is common in software fuzzing). However, I didn't check whether there is a real difference in the performance in choosing +1 or +0.01.  Prioritizing newly found seeds can be good in the early stage, but may not bring benefits in the latter stage. As in the latter stage, some seeds can just jailbreak several templates, but they also append new seeds in the seed pooling. In that case, prioritizing newly found seeds may not be good. We have an in-progress work that deals with the always-prioritizing problem.

**Comment by romanlutz** [comment]
Thanks for elaborating. That's really helpful!
