### ISSUE TITLE
关于judge model

### ISSUE THREAD

**Issue by hmppt** [sherdencooper/GPTFuzz#34]
你好，你们的工作对我来说非常有用！
我想请问一下，如果我只是需要用你们微调的bert模型来做judge model的话，我应该怎么操作？类似于让这个模型来做是否越狱成功的判断。

**Comment by hmppt** [comment]
具体来说，我的代码如下`

```
def JudgeModel(response):
    model_path = '/model/GPTFuzz'
    model = RoBERTaPredictor(model_path)

    judge_response = model.predict(response)
    print(response, judge_response[0])
    return judge_response[0]
```
我发现不管response是什么内容，他都会返回0。我希望能够获得更多相关的信息，包括在什么情况下，他会判断为越狱成功

**Comment by hmppt** [comment]
我貌似get到了，微调的roberta似乎不支持中文输入

**Comment by sherdencooper** [comment]
@hmppt 你好,感谢关注我们的工作,我们微调的bert model的确没有中文的语料训练,所以对于中文的确效果不好.如果想判断中文的话可以用gpt4omini判断,我们自己也测试了下发现效果还行

**Comment by hmppt** [comment]
感谢回答
